import FormInput from './FormInput'
import SectionCard from './SectionCard'

function ExperienceInformation({ records, errors, onChange, onAdd, onRemove }) {
  return <SectionCard number="05" title="Experience" description="Share internships, part-time roles, or full-time work experience."><div className="record-list">{records.map((record, index) => 
  <div className="record-block" key={`experience-${index}`}>
    <div className="record-title"><h3>Experience {index + 1}</h3>{records.length > 1 && <button className="btn btn-link remove-button" type="button" onClick={() => onRemove(index)}>Remove</button>}</div><div className="row"><div className="col-md-6"><FormInput label="Company name" name={`company-${index}`} value={record.company} onChange={(value) => onChange(index, 'company', value)} error={errors[index]?.company} /></div><div className="col-md-6"><FormInput label="Job / internship role" name={`role-${index}`} value={record.role} onChange={(value) => onChange(index, 'role', value)} error={errors[index]?.role} /></div><div className="col-md-6"><FormInput label="Start date" name={`startDate-${index}`} type="date" value={record.startDate} onChange={(value) => onChange(index, 'startDate', value)} error={errors[index]?.startDate} /></div><div className="col-md-6"><FormInput label="End date" name={`endDate-${index}`} type="date" value={record.endDate} onChange={(value) => onChange(index, 'endDate', value)} error={errors[index]?.endDate} /></div><div className="col-12"><FormInput label="Responsibilities" name={`responsibilities-${index}`} value={record.responsibilities} onChange={(value) => onChange(index, 'responsibilities', value)} error={errors[index]?.responsibilities} rows={4} placeholder="Describe your impact and responsibilities" /></div></div></div>)}</div><button className="btn btn-outline-primary add-button" type="button" onClick={onAdd}><span aria-hidden="true">+</span> Add another experience</button></SectionCard>
}

export default ExperienceInformation